# Generated by Django 4.2 on 2023-09-10 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('desc', models.TextField(max_length=10000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='products/images/')),
                ('is_active', models.BooleanField(default=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('flag', models.CharField(choices=[('Hot Coffee', 'Hot Coffee'), ('Cold Coffee', 'Cold Coffee')], max_length=20)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
